Add backup-server workload, use for bootstrapping trust for now
The intention is to also serve a tarball with everything needed
to rebuild a cluster with the same private keys and certificates

diff --git a/bin/auth b/bin/auth
--- a/bin/auth
+++ b/bin/auth
@@ -6,6 +6,7 @@ source "$PKGROOT/.upkg/records.sh/records.sh"
 
 KUBE_CFG_DEFAULT_PATH=$HOME/.kube/config.yaml
 CONFIG_DIR=$HOME/.config/phxc
+ROOT_CRT_PATH=$CONFIG_DIR/phoenix-cluster-root.crt
 
 main() {
   DOC="auth
@@ -39,30 +40,52 @@ done;eval $p'__username=${var___username:-system:admin};'$p'_ssh_keyname_=${va'\
 "${varnames[@]}"; do declare -p "$p$varname";done;done;}
 # docopt parser above, complete command for generating this parser is `docopt.sh --library='"$PKGROOT/.upkg/docopt-lib-v$v/docopt-lib.sh"' auth`
   eval "$(docopt "$@")"
-  local kube_api_addr kube_api_addr ca_url
+  local kube_api_addr backup_server_url kube_api_addr ca_url
   [[ ! $_kube_api_hostname_ =~ ^(https?://)?([^:]+) ]] || _kube_api_hostname_=${BASH_REMATCH[2]}
+  backup_server_url=https://$_kube_api_hostname_:8050
   kube_api_addr=https://$_kube_api_hostname_:6443
   ca_url=https://$_kube_api_hostname_:9001
 
+  curl_backup_server() {
+    local path=$1
+    shift
+    curl --no-progress-meter --cacert "$ROOT_CRT_PATH" \
+        --connect-to "backup-server.phxc.svc.cluster.local:8050:${_kube_api_hostname_}:8050" \
+        "https://backup-server.phxc.svc.cluster.local:8050/$path" "$@"
+  }
+
   # shellcheck disable=SC2154
   if $configure; then
-    trap 'error "Failed to configure, run with LOGLEVEL=verbose to see more details errors"' ERR
+    local yesno phxc_root_crt phxc_root_crt_fp
+    trap 'error "Failed to configure, run with LOGLEVEL=verbose to see more detailed errors"' ERR
     mkdir -p "$CONFIG_DIR"
-    local kube_api_server_cert kube_api_client_ca_fp yesno
+    # TOFU for phoenix cluster root CA
+    phxc_root_crt=$(curl -k --no-progress-meter "$backup_server_url/certs/phoenix-cluster-root.crt")
+    phxc_root_crt_fp=$(step certificate fingerprint <(printf "%s\n" "$phxc_root_crt"))
+    if [[ -e "$ROOT_CRT_PATH" ]]; then
+      local remote_phxc_root_crt_fp
+      remote_phxc_root_crt_fp=$(step certificate fingerprint "$ROOT_CRT_PATH")
+      if [[ $phxc_root_crt_fp != "$remote_phxc_root_crt_fp" ]]; then
+        printf "Saved fingerprint:  %s\n" "$phxc_root_crt_fp" >&2
+        printf "Remote fingerprint: %s\n" "$remote_phxc_root_crt_fp" >&2
+        error "The saved Phoenix Cluster root certificate fingerprint does not match the one from the server!"
+        [[ $(read -rp 'Are you sure you want to continue? [y/N]' yesno; echo "$yesno") =~ ^[Yy](es)?$ ]] || { trap '' ERR; fatal "User aborted operation"; }
+      fi
+    else
+      warning "No trust has been established with this Phoenix Cluster yet.\nThe root certificate fingerprint is %s" "$phxc_root_crt_fp"
+      [[ $(read -rp 'Do you want to establish that trust now? [y/N]' yesno; echo "$yesno") =~ ^[Yy](es)?$ ]] || { trap '' ERR; fatal "User aborted operation"; }
+    fi
+    printf "%s\n" "$phxc_root_crt" >"$ROOT_CRT_PATH"
+
+    local kube_api_server_ca_cert kube_api_client_ca_fp
+    kube_api_client_ca_fp=$(step certificate fingerprint <(curl_backup_server certs/kube-apiserver-client-ca-cert.crt) 2> >(LOGPROGRAM=step pipe_verbose))
+    kube_api_server_ca_cert=$(curl_backup_server certs/kube-apiserver-server-ca-cert.crt 2> >(LOGPROGRAM=step pipe_verbose))
+
     local kube_cfg_path=$HOME/.kube/phxc.yaml kube_context=phxc kube_cluster=phxc
-    # TOFU for both the api server & client certs
-    kube_api_client_ca_fp=$(step certificate fingerprint <(curl -k --no-progress-meter "$ca_url/roots.pem") 2> >(LOGPROGRAM=step pipe_verbose))
-    kube_api_server_cert=$(step certificate inspect --insecure --format pem "$kube_api_addr" 2> >(LOGPROGRAM=step pipe_verbose))
-    warning "The Kubernetes API server and client CA certificate fingerprints are:"
-    printf "Server:    %s\n" "$(step certificate fingerprint <(printf "%s\n" "$kube_api_server_cert"))" >&2
-    printf "Client CA: %s\n" "$kube_api_client_ca_fp" >&2
-    printf "Do you want to establish trust with these certificates? [y/N]"
-    read -r yesno
-    [[ $yesno =~ ^[Yy](es)?$ ]] || fatal "User aborted operation"
     kubectl config --kubeconfig "$kube_cfg_path" set-cluster "$kube_cluster" \
       --server="$kube_api_addr" \
       --embed-certs \
-      --certificate-authority=<(printf "%s" "$kube_api_server_cert")
+      --certificate-authority=<(printf "%s" "$kube_api_server_ca_cert")
     kubectl config --kubeconfig "$kube_cfg_path" set-credentials "$__username@$kube_cluster" \
       --exec-api-version="client.authentication.k8s.io/v1beta1" \
       --exec-command="$(realpath "${BASH_SOURCE[0]}")" \
@@ -75,7 +98,7 @@ done;eval $p'__username=${var___username:-system:admin};'$p'_ssh_keyname_=${va'\
       --cluster "$kube_cluster" --user "$__username@$kube_cluster"
     rm -f "$CONFIG_DIR/$__username.crt" "$CONFIG_DIR/$__username.key"
   elif $get_cert; then
-    trap 'error "Failed to get certificate, run with LOGLEVEL=verbose to see more details errors"' ERR
+    trap 'error "Failed to get certificate, run with LOGLEVEL=verbose to see more detailed errors"' ERR
     if [[ ! -e $CONFIG_DIR/$__username.crt ]] || \
         step certificate needs-renewal --expires-in 0s "$CONFIG_DIR/$__username.crt" 2>&1 | LOGPROGRAM=step pipe_verbose; then
       local kube_api_client_ca_cert remote_kube_api_client_ca_fp ssh_pem admin_jwk kid header payload signature step_logs
