node: Make remote attestation part of systemd startup again

diff --git a/workloads/node/bin/cluster-auth b/workloads/node/bin/cluster-auth
--- a/workloads/node/bin/cluster-auth
+++ b/workloads/node/bin/cluster-auth
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 # shellcheck source-path=../../..
 # Source: https://github.com/osresearch/safeboot-attest
+
 # safeboot-attest: TPM2 Remote Attestation
 #
 # This wraps the low level `tpm2-tools` programs into a fairly turn-key
@@ -9,9 +10,6 @@
 # sealed secret that can only be decrypted if the system is still in
 # that state.
 #
-# The external programs used are:
-# xxd, mktemp, tpm2, rm, date printf cp, curl, dd, openssl, cat
-#
 # For more info: https://safeboot.dev/attestation/
 set -Eeo pipefail; shopt -s inherit_errexit
 PKGROOT=$(realpath "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/../../..")
@@ -19,38 +17,34 @@ export LC_ALL=C
 
 main() {
   source "$PKGROOT/.upkg/records.sh/records.sh"
-  DOC="attest - Send a PCR quote to an attestation server and get a secret in return
+  DOC="cluster-auth - Use remote attestation to authenticate with the cluster
 Usage:
-  attest [-d --pcrs PCRs] attest ATTESTATION_URL
-  attest [--pcrs PCRs] generate-quote
+  cluster-auth [-d -r S] login
+  cluster-auth generate-quote
 
 Options:
-  -d --debug-response  Debug the server response
-  --pcrs PCRs          Comma-separated list of PCRs to generate a quote for
-                       [default: 0,1,2,3,4]
+  -d --debug-response  Debug the boot-server response
+  -r --retry=S         Retry attestation every S seconds until successful
 "
-# docopt parser below, refresh this parser with `docopt.sh safeboot-attest`
+# docopt parser below, refresh this parser with `docopt.sh cluster-auth`
 # shellcheck disable=2016,2086,2317,1090,1091,2034
 docopt() { local v='2.0.1'; source \
 "$PKGROOT/.upkg/docopt-lib-v$v/docopt-lib.sh" "$v" || { ret=$?;printf -- "exit \
-%d\n" "$ret";exit "$ret";};set -e;trimmed_doc=${DOC:0:350};usage=${DOC:78:93}
-digest=d7cbd;options=('-d --debug-response 0' ' --pcrs 1');node_0(){ switch \
-__debug_response 0;};node_1(){ value __pcrs 1;};node_2(){ value \
-ATTESTATION_URL a;};node_3(){ switch attest a:attest;};node_4(){ switch \
-generate_quote a:generate-quote;};node_5(){ sequence 6 3 2;};node_6(){
-optional 0 1;};node_7(){ sequence 8 4;};node_8(){ optional 1;};node_9(){
-choice 5 7;};cat <<<' docopt_exit() { [[ -n $1 ]] && printf "%s\n" "$1" >&2
-printf "%s\n" "${DOC:78:93}" >&2;exit 1;}';local varnames=(__debug_response \
-__pcrs ATTESTATION_URL attest generate_quote) varname;for varname in \
-"${varnames[@]}"; do unset "var_$varname";done;parse 9 "$@";local \
+%d\n" "$ret";exit "$ret";};set -e;trimmed_doc=${DOC:0:276};usage=${DOC:71:67}
+digest=12b9d;options=('-d --debug-response 0' '-r --retry 1');node_0(){ switch \
+__debug_response 0;};node_1(){ value __retry 1;};node_2(){ switch login a:login
+};node_3(){ switch generate_quote a:generate-quote;};node_4(){ sequence 5 2;}
+node_5(){ optional 0 1;};node_6(){ choice 4 3;};cat <<<' docopt_exit() { [[ -n \
+$1 ]] && printf "%s\n" "$1" >&2;printf "%s\n" "${DOC:71:67}" >&2;exit 1;}'
+local varnames=(__debug_response __retry login generate_quote) varname;for \
+varname in "${varnames[@]}"; do unset "var_$varname";done;parse 6 "$@";local \
 p=${DOCOPT_PREFIX:-''};for varname in "${varnames[@]}"; do unset "$p$varname"
-done;eval $p'__debug_response=${var___debug_response:-false};'$p'__pcrs=${var_'\
-'__pcrs:-0,1,2,3,4};'$p'ATTESTATION_URL=${var_ATTESTATION_URL:-};'$p'attest=${'\
-'var_attest:-false};'$p'generate_quote=${var_generate_quote:-false};';local \
-docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
+done;eval $p'__debug_response=${var___debug_response:-false};'$p'__retry=${var'\
+'___retry:-};'$p'login=${var_login:-false};'$p'generate_quote=${var_generate_q'\
+'uote:-false};';local docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
 ((;docopt_i>0;docopt_i--)); do for varname in "${varnames[@]}"; do declare -p \
 "$p$varname";done;done;}
-# docopt parser above, complete command for generating this parser is `docopt.sh --library='"$PKGROOT/.upkg/docopt-lib-v$v/docopt-lib.sh"' safeboot-attest`
+# docopt parser above, complete command for generating this parser is `docopt.sh --library='"$PKGROOT/.upkg/docopt-lib-v$v/docopt-lib.sh"' cluster-auth`
   eval "$(docopt "$@")"
 
   TPM2_QUIET='--quiet'
@@ -61,24 +55,42 @@ docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
 
   mkdir "$TMP/quote"
   # shellcheck disable=SC2154
-  if $attest; then
-    generate_quote "$__pcrs"
-    local file form_opts=()
-    for file in "$TMP/quote"/*; do
-      form_opts+=(--form "$(basename "$file")=@$file")
+  if $login; then
+    while true; do
+      local attestation_url
+      attestation_url=$(get_attestation_url)
+      generate_quote "1,2,3,4"
+      local file form_opts=()
+      for file in "$TMP/quote"/*; do
+        form_opts+=(--form "$(basename "$file")=@$file")
+      done
+      info "Sending quote to %s" "$attestation_url"
+      if ! curl -X POST -fs "${form_opts[@]}" "$attestation_url" > "$TMP/reply"; then
+        if [[ -n $__retry ]]; then
+          info "Attestation failed, retrying in %d seconds" "$__retry"
+          # shellcheck disable=SC2086
+          sleep $__retry
+        else
+          fatal "Attestation failed"
+        fi
+      else
+        ! $__debug_response || cat "$TMP/reply"
+        unseal_response >/run/initramfs/cluster-secrets.json
+        break
+      fi
     done
-    info "Sending quote to %s" "$ATTESTATION_URL"
-    # shellcheck disable=SC2154
-    if $__debug_response; then
-      curl -X POST -f "${form_opts[@]}" "$ATTESTATION_URL"
-    else
-      curl -X POST -fs "${form_opts[@]}" "$ATTESTATION_URL" > "$TMP/reply" || fatal $? "Attestation failed"
-      unseal_response || fatal $? "Failed to unseal the response"
-    fi
+    info "Attestation succeeded"
   elif $generate_quote; then
     generate_quote "$__pcrs"
     (cd "$TMP/quote"; tar -c -- *)
   fi
+}
+
+get_attestation_url() {
+  local boot_server_ip
+  boot_server_ip=$(jq -r .next_server /run/initramfs/boot-state.json)
+  [[ -n $boot_server_ip ]] || fatal "Unable to retrieve boot-server IP from /run/initramfs/boot-state.json"
+  printf "http://%s/attest" "$boot_server_ip"
 }
 
 tpm2_flushall() {
