node: Implement disk encryption config, generalize node-state, improve mount-boot in initramfs

diff --git a/workloads/node/bin/disk b/workloads/node/bin/disk
--- a/workloads/node/bin/disk
+++ b/workloads/node/bin/disk
@@ -3,19 +3,15 @@
 set -Eeo pipefail; shopt -s inherit_errexit
 PKGROOT=$(realpath "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/../../..")
 
-DISK_UUID=caf66bff-edab-4fb1-8ad9-e570be5415d7
-ESP_UUID=c12a7328-f81f-11d2-ba4b-00a0c93ec93b
-DATA_UUID=6f07821d-bb94-4d0f-936e-4060cadf18d8
-
 main() {
   source "$PKGROOT/.upkg/records.sh/records.sh"
   source "$PKGROOT/workloads/node/bootstrap/assets/etc/initramfs-tools/scripts/node-state.sh"
+  source "$PKGROOT/workloads/node/bootstrap/assets/etc/initramfs-tools/scripts/disk.sh"
 
   DOC="disk - Manage the disk for persisting data
 Usage:
-  disk get-devpath
   disk mount-boot
-  disk setup DEVPATH
+  disk setup
 "
 # docopt parser below, refresh this parser with `docopt.sh disk`
 # shellcheck disable=2016,2086,2317,1090,1091,2034
@@ -40,59 +36,26 @@ for ((;docopt_i>0;docopt_i--)); do for varname in "${varnames[@]}"; do declare \
   local devpath boot_devpath
 
   # shellcheck disable=SC2154
-  if $get_devpath; then
-    find_disk || fatal "No initialized disk for persisting data found"
-  elif $mount_boot; then
-    devpath=$(find_disk)
-    [[ -n $devpath ]] || fatal "No initialized disk for persisting data found"
+  if $mount_boot; then
+    devpath=$(get_node_config disk.devpath) || devpath=$(find_disk) || fatal "No initialized disk for persisting data found"
     boot_devpath=$(get_boot_devpath "$devpath")
     verbose "Mounting boot partition"
     mount "$boot_devpath" /boot
   elif $setup; then
+    local devpaths=()
+    devpath=$(get_node_config disk.devpath) || fatal "Unable to setup disk, no devpath provided in node-config.json"
+    if lsblk -Jndo PTUUID,NAME "$devpath" | jq -re --arg disk_uuid $DISK_UUID '.blockdevices[0].ptuuid==$disk_uuid' >/dev/null; then
+      info "disk at '%s' is already setup" "$devpath"
+    fi
+    if sfdisk -J "$devpath" 2>/dev/null || lsblk -Jndo FSTYPE "$devpath" | jq -re '.blockdevices[0].fstype != null' >/dev/null; then
+      get_node_config disk.force || fatal "Device %s is partitioned or contains a filesystem and .disk.force!=true, aborting disk setup"
+    fi
+    wipefs -a "$devpath"
     # shellcheck disable=SC2153
-    partition_disk "$DEVPATH"
-    boot_devpath=$(get_boot_devpath "$DEVPATH")
+    partition_disk "$devpath"
+    boot_devpath=$(get_boot_devpath "$devpath")
     mkfs.vfat "$boot_devpath"
-  fi
-}
-
-get_boot_devpath() {
-  local devpath=$1
-  printf "/dev/%s" "$(lsblk -Jno Name "$devpath" | jq -re '.blockdevices[0].children[0].name')"
-}
-
-find_disk() {
-  local devnames=()
-  readarray -t -d $'\n' devnames < <(lsblk -Jndo PTUUID,NAME -a | jq -r --arg disk_uuid $DISK_UUID '.blockdevices[] | select(.ptuuid==$disk_uuid) | .name')
-  if [[ ${#devnames[@]} -eq 1 ]]; then
-    info "Disk found at %s" "$devpath"
-    printf "/dev/%s" "${devnames[0]}"
-  elif [[ ${#devnames[@]} -gt 1 ]]; then
-    fatal "Found multiple disks marked with the UUID '%s'" "$DISK_UUID"
-  fi
-}
-
-find_largest_blank_disk() {
-  local devname devnames=()
-  for devname in $(lsblk --json --output NAME,FSTYPE,TYPE,MAJ:MIN | jq -r '.blockdevices[] | select(.fstype==null and .type=="disk" and (.["maj:min"] | endswith(":0"))) | .name'); do
-    sfdisk -J "/dev/$devname" &>/dev/null || devnames+=("$devname")
-  done
-
-  if [[ ${#devnames[@]} -eq 1 ]]; then
-    info "Choosing /dev/%s for persisting data" "${devnames[0]}"
-    printf "/dev/%s" "${devnames[0]}"
-  elif [[ ${#devnames[@]} -gt 1 ]]; then
-    warning 'Multiple blank disks for persisting data found (%s), determining the largest' "${devnames[*]}"
-    local largest_devsize=0 largest_devname devsize
-    for devname in "${devnames[@]}"; do
-      devsize=$(lsblk -nb --output SIZE "/dev/$devname")
-      if (( devsize > largest_devsize )); then
-        largest_devsize=$devsize
-        largest_devname=$devname
-      fi
-    done
-    info "Choosing /dev/%s for persisting data" "$largest_devname"
-    printf "/dev/%s" "$largest_devname"
+    set_node_state disk.devpath "$devpath"
   fi
 }
 
