node: Get secret unsealing working

diff --git a/workloads/node/bin/safeboot-attest b/workloads/node/bin/safeboot-attest
--- a/workloads/node/bin/safeboot-attest
+++ b/workloads/node/bin/safeboot-attest
@@ -70,9 +70,9 @@ docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
     info "Sending quote to %s" "$ATTESTATION_URL"
     # shellcheck disable=SC2154
     if $__debug_response; then
-      curl -X POST -f "${form_opts[@]}" "$ATTESTATION_URL" > "$TMP/secret"
+      curl -X POST -f "${form_opts[@]}" "$ATTESTATION_URL"
     else
-      curl -X POST -fs "${form_opts[@]}" "$ATTESTATION_URL" || fatal $? "Attestation failed"
+      curl -X POST -fs "${form_opts[@]}" "$ATTESTATION_URL" > "$TMP/secret" || fatal $? "Attestation failed"
       unseal_response "$TMP/secret"
     fi
   elif $generate_quote; then
@@ -91,9 +91,9 @@ tpm2_flushall() {
     LOGPROGRAM=tpm2 pipe_verbose || fatal $? "tpm2_flushcontext: unable to flush saved session"
 }
 
-tpm2_secret_session() {
+tpm2_session() {
   tpm2_flushall
-  verbose "tpm2: starting secret session"
+  verbose "tpm2: starting session"
   tpm2 startauthsession $TPM2_QUIET --session "$TMP/session.ctx" --policy-session 2>&1 | \
     LOGPROGRAM=tpm2 pipe_verbose || fatal $? "tpm2_startauthsession: unable to start authenticated session"
   # context is TPM_RH_ENDORSEMENT because why would you want names?
@@ -116,7 +116,7 @@ generate_quote() {
   #   --ek-public "$TMP/quote/ek.pub" -o ek.crt 2>&1 | \
   #   LOGPROGRAM=tpm2 pipe_verbose || fatal $? "tpm2_getekcertificate: unable to retrieve endorsement certificate"
 
-  tpm2_secret_session
+  tpm2_session
   verbose "Creating ephemeral attestation key"
   tpm2 create $TPM2_QUIET --parent-context "$TMP/ek.ctx" --parent-auth "session:$TMP/session.ctx" \
     --key-algorithm "ecc:ecdsa:null" \
@@ -125,7 +125,7 @@ generate_quote() {
     LOGPROGRAM=tpm2 pipe_verbose || fatal $? "tpm2_create: unable to create an attestation key"
 
   # have to start a new secret session to load the attestation key
-  tpm2_secret_session
+  tpm2_session
   tpm2 load >&2 \
     $TPM2_QUIET \
     --parent-context "$TMP/ek.ctx" \
@@ -188,11 +188,13 @@ unseal_response() {
   REPLY="$1"
   info "Unsealing response"
 
-  dd if="$REPLY" of="$TMP/cred.blob" bs=16 skip=0 count=23 2>&-
-  dd if="$REPLY" of="$TMP/hmac.bin" bs=16 skip=23 count=2 2>&-
-  dd if="$REPLY" of="$TMP/cipher.bin" bs=16 skip=25 2>&-
+  # See attest-server.py for the reuse of the IV as an HMAC
 
-  tpm2_secret_session
+  dd if="$REPLY" status=none bs=16 skip=0  count=22 of="$TMP/cred.blob"
+  dd if="$REPLY" status=none bs=16 skip=22 count=2  of="$TMP/hmac.bin"
+  dd if="$REPLY" status=none bs=16 skip=24          of="$TMP/cipher.bin"
+
+  tpm2_session
 
   tpm2 activatecredential \
     $TPM2_QUIET \
@@ -204,18 +206,19 @@ unseal_response() {
     LOGPROGRAM=tpm2 pipe_verbose || fatal $? "tpm2_activatecredential: unable to unseal key"
 
   # split the secret.key into AES key and IV,
-  dd if="$TMP/secret.key" bs=16 skip=0 count=2 of="$TMP/aes.key" 2>&-
-  dd if="$TMP/secret.key" bs=16 skip=2 count=1 of="$TMP/aes.iv" 2>&-
-  dd if="$TMP/secret.key" bs=16 skip=3 count=1 of="$TMP/hmac.key" 2>&-
+  dd if="$TMP/secret.key" bs=16 skip=0 count=2 status=none of="$TMP/aes.key"
+  dd if="$TMP/secret.key" bs=16 skip=2 count=1 status=none of="$TMP/aes.iv"
+  dd if="$TMP/secret.key" bs=16 skip=2 count=1 status=none of="$TMP/hmac.key"
+  # dd if="$TMP/secret.key" bs=16 skip=3 count=1 status=none of="$TMP/hmac.key"
 
   # validate the hmac on the reply
   verbose "Validating reply"
   openssl dgst \
-    -sha256 -binary -mac hmac -macopt hexkey:"$(xxd -p -c128 "$TMP/hmac.key")" \
+    -sha256 -binary -mac hmac -macopt hexkey:"$(xxd -p -c0 "$TMP/hmac.key")" \
     -out "$TMP/hmac.out" "$TMP/cipher.bin" 2>&1 | \
-    LOGPROGRAM=openssl pipe_verbose || fatal $? "unable to hmac reply"
+    LOGPROGRAM=openssl pipe_verbose || fatal $? "Failed to create hmac of reply"
 
-  cmp --quiet "$TMP/hmac.out" "$TMP/hmac.bin" || fatal $? "hmac failed"
+  cmp --quiet "$TMP/hmac.out" "$TMP/hmac.bin" || fatal $? "hmac comparison failed"
 
   # hmac validated, so the encrypted data should be
   # safe to decrypt with the session key, writing to stdout
