cli: Bootstrap in parallel filtered by variant, detect failed updates

diff --git a/cli/bin/phxc b/cli/bin/phxc
--- a/cli/bin/phxc
+++ b/cli/bin/phxc
@@ -14,7 +14,7 @@ main() {
   DOC="phxc - Phoenix Cluster management tool
 Usage:
   phxc setup [-k KN -u UN] KUBEAPI_HOSTNAME
-  phxc bootstrap [--wait|--update] VARIANT
+  phxc bootstrap [--wait|--update] [VARIANT]...
   phxc update-nodes (all | NODE...)
   phxc recovery-keys
   phxc embed-configs IMAGE CLUSTER [NODE [RPIOTP]]
@@ -28,7 +28,7 @@ Options:
 
 Commands:
   setup          Setup the Phoenix Cluster root trust and configure kubectl
-  bootstrap      Manually start a bootstrap job for VARIANT
+  bootstrap      Manually start bootstrapping jobs (filtered by VARIANT)
   update-node    Update the node with the latest bootstrapped image
   recovery-keys  Show the disk-encryption recovery keys
   embed-configs  Embed configuration in the FAT32 partition of a disk image
@@ -38,39 +38,40 @@ Commands:
 # shellcheck disable=2016,2086,2317,1090,1091,2034,2154
 docopt() { local v='2.0.2'; source \
 "$PKGROOT/.upkg/docopt-lib-v$v/docopt-lib.sh" "$v" || { ret=$?;printf -- "exit \
-%d\n" "$ret";exit "$ret";};set -e;trimmed_doc=${DOC:0:975};usage=${DOC:39:253}
-digest=a420c;options=('-k --ssh-keyname 1' '-u --username 1' ' --wait 0' ' --u'\
+%d\n" "$ret";exit "$ret";};set -e;trimmed_doc=${DOC:0:993};usage=${DOC:39:258}
+digest=91d9f;options=('-k --ssh-keyname 1' '-u --username 1' ' --wait 0' ' --u'\
 'pdate 0');node_0(){ value __ssh_keyname 0;};node_1(){ value __username 1;}
 node_2(){ switch __wait 2;};node_3(){ switch __update 3;};node_4(){ value \
-KUBEAPI_HOSTNAME a;};node_5(){ value VARIANT a;};node_6(){ value NODE a true;}
-node_7(){ value IMAGE a;};node_8(){ value CLUSTER a;};node_9(){ value RPIOTP a;}
-node_10(){ switch setup a:setup;};node_11(){ switch bootstrap a:bootstrap;}
-node_12(){ switch update_nodes a:update-nodes;};node_13(){ switch all a:all;}
-node_14(){ switch recovery_keys a:recovery-keys;};node_15(){ switch \
-embed_configs a:embed-configs;};node_16(){ switch get_kube_cert a:get-kube-cert
-};node_17(){ sequence 10 18 4;};node_18(){ optional 0 1;};node_19(){ sequence \
-11 20 5;};node_20(){ optional 21;};node_21(){ choice 2 3;};node_22(){ sequence \
-12 23;};node_23(){ choice 13 24;};node_24(){ repeatable 6;};node_25(){
-sequence 15 7 8 26;};node_26(){ optional 6 9;};node_27(){ sequence 16 18 4;}
-node_28(){ choice 17 19 22 14 25 27;};cat <<<' docopt_exit() { [[ -n $1 ]] && \
-printf "%s\n" "$1" >&2;printf "%s\n" "${DOC:39:253}" >&2;exit 1;}';local \
-varnames=(__ssh_keyname __username __wait __update KUBEAPI_HOSTNAME VARIANT \
-NODE IMAGE CLUSTER RPIOTP setup bootstrap update_nodes all recovery_keys \
-embed_configs get_kube_cert) varname;for varname in "${varnames[@]}"; do unset \
-"var_$varname";done;parse 28 "$@";local p=${DOCOPT_PREFIX:-''};for varname in \
-"${varnames[@]}"; do unset "$p$varname";done;if declare -p var_NODE >/dev/null \
-2>&1; then eval $p'NODE=("${var_NODE[@]}")';else eval $p'NODE=()';fi;eval $p'_'\
-'_ssh_keyname=${var___ssh_keyname:-'"'"'$USER@$HOST'"'"'};'$p'__username=${var'\
-'___username:-system:admin};'$p'__wait=${var___wait:-false};'$p'__update=${var'\
-'___update:-false};'$p'KUBEAPI_HOSTNAME=${var_KUBEAPI_HOSTNAME:-};'$p'VARIANT='\
-'${var_VARIANT:-};'$p'IMAGE=${var_IMAGE:-};'$p'CLUSTER=${var_CLUSTER:-};'$p'RP'\
-'IOTP=${var_RPIOTP:-};'$p'setup=${var_setup:-false};'$p'bootstrap=${var_bootst'\
-'rap:-false};'$p'update_nodes=${var_update_nodes:-false};'$p'all=${var_all:-fa'\
-'lse};'$p'recovery_keys=${var_recovery_keys:-false};'$p'embed_configs=${var_em'\
-'bed_configs:-false};'$p'get_kube_cert=${var_get_kube_cert:-false};';local \
-docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
-((;docopt_i>0;docopt_i--)); do for varname in "${varnames[@]}"; do declare -p \
-"$p$varname";done;done;}
+KUBEAPI_HOSTNAME a;};node_5(){ value VARIANT a true;};node_6(){ value NODE a \
+true;};node_7(){ value IMAGE a;};node_8(){ value CLUSTER a;};node_9(){ value \
+RPIOTP a;};node_10(){ switch setup a:setup;};node_11(){ switch bootstrap \
+a:bootstrap;};node_12(){ switch update_nodes a:update-nodes;};node_13(){
+switch all a:all;};node_14(){ switch recovery_keys a:recovery-keys;};node_15(){
+switch embed_configs a:embed-configs;};node_16(){ switch get_kube_cert \
+a:get-kube-cert;};node_17(){ sequence 10 18 4;};node_18(){ optional 0 1;}
+node_19(){ sequence 11 20 22;};node_20(){ optional 21;};node_21(){ choice 2 3;}
+node_22(){ repeatable 23;};node_23(){ optional 5;};node_24(){ sequence 12 25;}
+node_25(){ choice 13 26;};node_26(){ repeatable 6;};node_27(){ sequence 15 7 8 \
+28;};node_28(){ optional 6 9;};node_29(){ sequence 16 18 4;};node_30(){ choice \
+17 19 24 14 27 29;};cat <<<' docopt_exit() { [[ -n $1 ]] && printf "%s\n" "$1" \
+>&2;printf "%s\n" "${DOC:39:258}" >&2;exit 1;}';local varnames=(__ssh_keyname \
+__username __wait __update KUBEAPI_HOSTNAME VARIANT NODE IMAGE CLUSTER RPIOTP \
+setup bootstrap update_nodes all recovery_keys embed_configs get_kube_cert) \
+varname;for varname in "${varnames[@]}"; do unset "var_$varname";done;parse 30 \
+"$@";local p=${DOCOPT_PREFIX:-''};for varname in "${varnames[@]}"; do unset \
+"$p$varname";done;if declare -p var_VARIANT >/dev/null 2>&1; then eval $p'VARI'\
+'ANT=("${var_VARIANT[@]}")';else eval $p'VARIANT=()';fi;if declare -p var_NODE \
+>/dev/null 2>&1; then eval $p'NODE=("${var_NODE[@]}")';else eval $p'NODE=()';fi
+eval $p'__ssh_keyname=${var___ssh_keyname:-'"'"'$USER@$HOST'"'"'};'$p'__userna'\
+'me=${var___username:-system:admin};'$p'__wait=${var___wait:-false};'$p'__upda'\
+'te=${var___update:-false};'$p'KUBEAPI_HOSTNAME=${var_KUBEAPI_HOSTNAME:-};'\
+$p'IMAGE=${var_IMAGE:-};'$p'CLUSTER=${var_CLUSTER:-};'$p'RPIOTP=${var_RPIOTP:-'\
+'};'$p'setup=${var_setup:-false};'$p'bootstrap=${var_bootstrap:-false};'$p'upd'\
+'ate_nodes=${var_update_nodes:-false};'$p'all=${var_all:-false};'$p'recovery_k'\
+'eys=${var_recovery_keys:-false};'$p'embed_configs=${var_embed_configs:-false}'\
+';'$p'get_kube_cert=${var_get_kube_cert:-false};';local docopt_i=1;[[ \
+$BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for ((;docopt_i>0;docopt_i--)); do for \
+varname in "${varnames[@]}"; do declare -p "$p$varname";done;done;}
 # docopt parser above, complete command for generating this parser is `docopt.sh --library='"$PKGROOT/.upkg/docopt-lib-v$v/docopt-lib.sh"' phxc`
   eval "$(docopt "$@")"
 
@@ -91,7 +92,7 @@ docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
   elif $recovery_keys; then
     recovery_keys
   elif $bootstrap; then
-    bootstrap "$VARIANT" "$__wait" "$__update"
+    bootstrap "$__wait" "$__update" "${VARIANT[@]}"
   elif $update_nodes; then
     nodes=()
     if $all; then
@@ -285,29 +286,45 @@ recovery_keys() {
 }
 
 bootstrap() {
-  local variant=$1 wait=$2 update=$3 job_name
-  job_name="build-$variant-$(date --utc +%Y%m%d%H%M%S)"
-  info "Creating job %s" "$job_name"
-  kubectl --context phxc -n phxc create job --from="cronjob/build-$variant" "$job_name"
-  if $wait || $update; then
-    info "Waiting for %s to complete" "$job_name"
-    kubectl --context phxc -n phxc wait --timeout=-1s --for=condition=Complete job "$job_name"
-    info "Bootstrap job for %s completed" "$variant"
+  local wait=$1 update=$2 variants=()
+  shift; shift
+  if [[ $# -gt 0 ]]; then
+    variants=("$@")
+  else
+    # shellcheck disable=SC2207
+    variants=($(kubectl --context phxc get node -ojsonpath='{.items.*.metadata.labels.cluster\.local/variant}'))
   fi
-  # shellcheck disable=SC2046
-  if $update; then
-    info "Updating all %s nodes" "$variant"
-    update_nodes $(kubectl --context phxc get nodes --selector="cluster.local/variant=$variant" -ojsonpath='{.items[*].metadata.name}')
+  local variant job_name
+  declare -A jobs
+  for variant in "${variants[@]}"; do
+    job_name="build-$variant-$(date --utc +%Y%m%d%H%M%S)"
+    info "Creating job %s" "$job_name"
+    kubectl --context phxc -n phxc create job --from="cronjob/build-$variant" "$job_name"
+    jobs[$variant]=$job_name
+  done
+  if $wait || $update; then
+    for variant in "${!jobs[@]}"; do
+      job_name=${jobs[$variant]}
+      info "Waiting for %s to complete" "$job_name"
+      kubectl --context phxc -n phxc wait --timeout=-1s --for=condition=Complete job "$job_name"
+      info "Bootstrap job for %s completed" "$variant"
+      # shellcheck disable=SC2046
+      if $update; then
+        info "Updating all %s nodes" "$variant"
+        update_nodes $(kubectl --context phxc get nodes --selector="cluster.local/variant=$variant" -ojsonpath='{.items[*].metadata.name}')
+      fi
+    done
   fi
 }
 
 update_nodes() {
-  local nodes=("$@") node hostname skipped_nodes=() unschedulable
+  local nodes=("$@") node hostname current_rootimg_sha256 new_rootimg_sha256 failed_nodes=() unschedulable
   if ! kubectl get node -ojson | jq -e '[.items[] | select(.spec.unschedulable)] | length == 0' >/dev/null; then
     fatal "Unable to update any nodes. Some nodes are currently unschedulable"
   fi
   for node in "${nodes[@]}"; do
     hostname=$(kubectl --context phxc get node "$node" -ojsonpath='{.metadata.labels.kubernetes\.io/hostname}')
+    current_rootimg_sha256=$(LC_ALL=C ssh "admin@$node" cat /run/initramfs/root.img.sha256)
     info "Updating %s" "$node"
     LC_ALL=C ssh "admin@$hostname" -- sudo systemctl start --no-block update-boot
     # shellcheck disable=SC2064
@@ -316,16 +333,23 @@ update_nodes() {
       sudo systemctl start update-boot
       sleep 2"' # Wait until the last few log entries are flushed
     if [[ $(kubectl get node "$node" -ojsonpath='{.spec.unschedulable}' 2>/dev/null) != 'true' ]]; then
-      skipped_nodes+=("$node")
+      failed_nodes+=("$node")
       continue
     fi
     # Node may be single master, so don't fail when kubectl fails
     until unschedulable=$(kubectl get node "$node" -ojsonpath='{.spec.unschedulable}' 2>/dev/null) && [[ $unschedulable != 'true' ]]; do
-      sleep 10
+      sleep 5
     done
+    new_rootimg_sha256=$(LC_ALL=C ssh "admin@$node" cat /run/initramfs/root.img.sha256)
+    if [[ $current_rootimg_sha256 = "$new_rootimg_sha256" ]]; then
+      info "%s failed to update to the new image (still on %s)" "$node" "$current_rootimg_sha256"
+      failed_nodes+=("$node")
+    else
+      info "%s successfully updated to the new image (updated from %s to %s)" "$node" "$current_rootimg_sha256" "$new_rootimg_sha256"
+    fi
   done
-  if [[ ${#skipped_nodes[@]} -gt 0 ]]; then
-    warning "Some nodes were not updated, see the logs above for details. The skipped nodes were:\n%s" "${skipped_nodes[*]}"
+  if [[ ${#failed_nodes[@]} -gt 0 ]]; then
+    warning "Some nodes were not updated, see the logs above for details. The failed nodes were:\n%s" "${failed_nodes[*]}"
   fi
 }
 
