phxc-cli: Add restore, bootstrap, and update-nodes commands

diff --git a/cli/bin/phxc b/cli/bin/phxc
--- a/cli/bin/phxc
+++ b/cli/bin/phxc
@@ -12,44 +12,64 @@ main() {
   DOC="phxc - Phoenix Cluster management tool
 Usage:
   phxc setup [-k KN -u UN] KUBEAPI_HOSTNAME
-  phxc secrets-backup
+  phxc bootstrap [--wait] VARIANT
+  phxc update-nodes (all | NODE...)
+  phxc backup-secrets [FILE]
+  phxc restore-secrets [FILE]
   phxc embed-configs IMAGE CLUSTER [NODE [RPIOTP]]
   phxc get-kube-cert [-k KN -u UN] KUBEAPI_HOSTNAME
 
 Options:
   -u --username=UN     K8S username to authenticate as [default: system:admin]
   -k --ssh-keyname=KN  SSH key to use for authentication [default: \$USER@\$HOST]
+  -w --wait            Wait for completion
 
 Commands:
-  setup         - Setup the Phoenix Cluster root trust and configure kubectl
-  embed-configs - Embed configuration in the FAT32 partition of a disk image
-  get-kube-cert - Issue or refresh a client cert for use with kubectl
+  setup           - Setup the Phoenix Cluster root trust and configure kubectl
+  bootstrap       - Manually start a bootstrap job for VARIANT
+  update-node     - Update the node with the latest bootstrapped image
+  backup-secrets  - Backup the phxc-ca and secureboot certs & keys
+  restore-secrets - Restore the phxc-ca and secureboot certs & keys
+  embed-configs   - Embed configuration in the FAT32 partition of a disk image
+  get-kube-cert   - Issue or refresh a client cert for use with kubectl
 "
 # docopt parser below, refresh this parser with `docopt.sh phxc`
-# shellcheck disable=2016,2086,2317,1090,1091,2034
+# shellcheck disable=2016,2086,2317,1090,1091,2034,2154
 docopt() { local v='2.0.2'; source \
 "$PKGROOT/.upkg/docopt-lib-v$v/docopt-lib.sh" "$v" || { ret=$?;printf -- "exit \
-%d\n" "$ret";exit "$ret";};set -e;trimmed_doc=${DOC:0:618};usage=${DOC:39:175}
-digest=1d05e;options=('-k --ssh-keyname 1' '-u --username 1');node_0(){ value \
-__ssh_keyname 0;};node_1(){ value __username 1;};node_2(){ value \
-KUBEAPI_HOSTNAME a;};node_3(){ value IMAGE a;};node_4(){ value CLUSTER a;}
-node_5(){ value NODE a;};node_6(){ value RPIOTP a;};node_7(){ switch setup \
-a:setup;};node_8(){ switch secrets_backup a:secrets-backup;};node_9(){ switch \
-embed_configs a:embed-configs;};node_10(){ switch get_kube_cert a:get-kube-cert
-};node_11(){ sequence 7 12 2;};node_12(){ optional 0 1;};node_13(){ sequence 9 \
-3 4 14;};node_14(){ optional 5 6;};node_15(){ sequence 10 12 2;};node_16(){
-choice 11 8 13 15;};cat <<<' docopt_exit() { [[ -n $1 ]] && printf "%s\n" "$1" \
->&2;printf "%s\n" "${DOC:39:175}" >&2;exit 1;}';local varnames=(__ssh_keyname \
-__username KUBEAPI_HOSTNAME IMAGE CLUSTER NODE RPIOTP setup secrets_backup \
-embed_configs get_kube_cert) varname;for varname in "${varnames[@]}"; do unset \
-"var_$varname";done;parse 16 "$@";local p=${DOCOPT_PREFIX:-''};for varname in \
-"${varnames[@]}"; do unset "$p$varname";done;eval $p'__ssh_keyname=${var___ssh'\
-'_keyname:-'"'"'$USER@$HOST'"'"'};'$p'__username=${var___username:-system:admi'\
-'n};'$p'KUBEAPI_HOSTNAME=${var_KUBEAPI_HOSTNAME:-};'$p'IMAGE=${var_IMAGE:-};'\
-$p'CLUSTER=${var_CLUSTER:-};'$p'NODE=${var_NODE:-};'$p'RPIOTP=${var_RPIOTP:-};'\
-$p'setup=${var_setup:-false};'$p'secrets_backup=${var_secrets_backup:-false};'\
-$p'embed_configs=${var_embed_configs:-false};'$p'get_kube_cert=${var_get_kube_'\
-'cert:-false};';local docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
+%d\n" "$ret";exit "$ret";};set -e;trimmed_doc=${DOC:0:1043};usage=${DOC:39:282}
+digest=1fdaf;options=('-k --ssh-keyname 1' '-u --username 1' '-w --wait 0')
+node_0(){ value __ssh_keyname 0;};node_1(){ value __username 1;};node_2(){
+switch __wait 2;};node_3(){ value KUBEAPI_HOSTNAME a;};node_4(){ value VARIANT a
+};node_5(){ value NODE a true;};node_6(){ value FILE a;};node_7(){ value IMAGE a
+};node_8(){ value CLUSTER a;};node_9(){ value RPIOTP a;};node_10(){ switch \
+setup a:setup;};node_11(){ switch bootstrap a:bootstrap;};node_12(){ switch \
+update_nodes a:update-nodes;};node_13(){ switch all a:all;};node_14(){ switch \
+backup_secrets a:backup-secrets;};node_15(){ switch restore_secrets \
+a:restore-secrets;};node_16(){ switch embed_configs a:embed-configs;};node_17(){
+switch get_kube_cert a:get-kube-cert;};node_18(){ sequence 10 19 3;};node_19(){
+optional 0 1;};node_20(){ sequence 11 21 4;};node_21(){ optional 2;};node_22(){
+sequence 12 23;};node_23(){ choice 13 24;};node_24(){ repeatable 5;};node_25(){
+sequence 14 26;};node_26(){ optional 6;};node_27(){ sequence 15 26;};node_28(){
+sequence 16 7 8 29;};node_29(){ optional 5 9;};node_30(){ sequence 17 19 3;}
+node_31(){ choice 18 20 22 25 27 28 30;};cat <<<' docopt_exit() { [[ -n $1 ]] \
+&& printf "%s\n" "$1" >&2;printf "%s\n" "${DOC:39:282}" >&2;exit 1;}';local \
+varnames=(__ssh_keyname __username __wait KUBEAPI_HOSTNAME VARIANT NODE FILE \
+IMAGE CLUSTER RPIOTP setup bootstrap update_nodes all backup_secrets \
+restore_secrets embed_configs get_kube_cert) varname;for varname in \
+"${varnames[@]}"; do unset "var_$varname";done;parse 31 "$@";local \
+p=${DOCOPT_PREFIX:-''};for varname in "${varnames[@]}"; do unset "$p$varname"
+done;if declare -p var_NODE >/dev/null 2>&1; then eval $p'NODE=("${var_NODE[@]'\
+'}")';else eval $p'NODE=()';fi;eval $p'__ssh_keyname=${var___ssh_keyname:-'\
+"'"'$USER@$HOST'"'"'};'$p'__username=${var___username:-system:admin};'$p'__wai'\
+'t=${var___wait:-false};'$p'KUBEAPI_HOSTNAME=${var_KUBEAPI_HOSTNAME:-};'$p'VAR'\
+'IANT=${var_VARIANT:-};'$p'FILE=${var_FILE:-};'$p'IMAGE=${var_IMAGE:-};'$p'CLU'\
+'STER=${var_CLUSTER:-};'$p'RPIOTP=${var_RPIOTP:-};'$p'setup=${var_setup:-false'\
+'};'$p'bootstrap=${var_bootstrap:-false};'$p'update_nodes=${var_update_nodes:-'\
+'false};'$p'all=${var_all:-false};'$p'backup_secrets=${var_backup_secrets:-fal'\
+'se};'$p'restore_secrets=${var_restore_secrets:-false};'$p'embed_configs=${var'\
+'_embed_configs:-false};'$p'get_kube_cert=${var_get_kube_cert:-false};';local \
+docopt_i=1;[[ $BASH_VERSION =~ ^4.3 ]] && docopt_i=2;for \
 ((;docopt_i>0;docopt_i--)); do for varname in "${varnames[@]}"; do declare -p \
 "$p$varname";done;done;}
 # docopt parser above, complete command for generating this parser is `docopt.sh --library='"$PKGROOT/.upkg/docopt-lib-v$v/docopt-lib.sh"' phxc`
@@ -69,8 +89,21 @@ $p'embed_configs=${var_embed_configs:-false};'$p'get_kube_cert=${var_get_kube_'\
     get_kube_client_cert "$KUBEAPI_HOSTNAME" "$__ssh_keyname" "$__username"
   elif $embed_configs; then
     embed_configs "$IMAGE" "$CLUSTER" "$NODE" "$RPIOTP"
-  elif $secrets_backup; then
-    secrets_backup
+  elif $backup_secrets; then
+    backup_secrets "$FILE"
+  elif $restore_secrets; then
+    restore_secrets "$FILE"
+  elif $bootstrap; then
+    bootstrap "$VARIANT" "$__wait"
+  elif $update_nodes; then
+    nodes=()
+    if $all; then
+      # shellcheck disable=SC2207
+      nodes=($(kubectl --context phxc get nodes -ojsonpath='{.items[*].metadata.name}'))
+    else
+      nodes=("${NODE[@]}")
+    fi
+    update_nodes "${nodes[@]}"
   fi
 }
 
@@ -135,7 +168,7 @@ trust_ssh_host_key() {
 
 get_kube_client_cert() {
   local kube_api_hostname=$1 ssh_keyname=$2 username=$3 cert key
-  refresh_cert "$kube_api_hostname" "$ssh_keyname" "$username"
+  renew_kube_client_cert "$kube_api_hostname" "$ssh_keyname" "$username"
   cert=$(cat "$CONFIG_DIR/$username.crt")
   key=$(cat "$CONFIG_DIR/$username.key")
   printf '{
@@ -149,12 +182,13 @@ get_kube_client_cert() {
 ' "${cert//$'\n'/'\n'}" "${key//$'\n'/'\n'}"
 }
 
-refresh_cert() {
+renew_kube_client_cert() {
   local kube_api_hostname=$1 ssh_keyname=$2 username=$3 ca_url
   trap 'error "Failed to get certificate, run with LOGLEVEL=verbose to see more detailed errors"' ERR
   ca_url=https://${kube_api_hostname}:9001
   if [[ ! -e $CONFIG_DIR/$username.crt ]] || \
       step certificate needs-renewal --expires-in 0s "$CONFIG_DIR/$username.crt" 2>&1 | LOGPROGRAM=step pipe_verbose; then
+    debug "Renewing client certificate"
     local ssh_pem admin_jwk kid header payload signature step_logs
     ssh_pem=$(step kms key "sshagentkms:$ssh_keyname" 2> >(LOGPROGRAM=step pipe_verbose))
     admin_jwk=$(step crypto jwk create --force --use sig --from-pem=<(printf "%s\n" "$ssh_pem") \
@@ -211,17 +245,95 @@ embed_configs() {
     ghcr.io/andsens/phxc-embed-configs:sha-3e0c5ff
 }
 
-secrets_backup() {
-  printf -- "# Phoenix Cluster secrets backup, restore with \`kubectl apply -f backup.yaml\` then restart all nodes and run \`phxc setup\` again\n"
-  printf -- "---\n"
-  kubectl --context phxc -n smallstep get secret phxc-root -ojson | \
-    jq 'del(.metadata.annotations) | del(.metadata.labels) | del(.metadata.resourceVersion) | del(.metadata.uid)'
-  printf -- "---\n"
-  kubectl --context phxc -n smallstep get secret phxc-intermediate -ojson | \
-    jq 'del(.metadata.annotations) | del(.metadata.labels) | del(.metadata.resourceVersion) | del(.metadata.uid)'
-  printf -- "---\n"
-  kubectl --context phxc -n phxc get secret secureboot -ojson | \
-    jq 'del(.metadata.annotations) | del(.metadata.labels) | del(.metadata.resourceVersion) | del(.metadata.uid)'
+backup_secrets() {
+  local dest=$1 backup
+  backup=$(
+    printf -- "# Phoenix Cluster secrets backup, restore with \`phxc restore secrets backup.yaml\`\n"
+    printf -- "---\n"
+    kubectl --context phxc -n smallstep get secret phxc-root -ojson | clean_cert_secret
+    printf -- "---\n"
+    kubectl --context phxc -n smallstep get secret phxc-intermediate -ojson | clean_cert_secret
+    printf -- "---\n"
+    kubectl --context phxc -n phxc get secret secureboot -ojson | clean_cert_secret
+  )
+  if [[ -n $dest ]]; then
+    (umask 0077; printf "%s\n" "$backup" >"$dest")
+  else
+    printf "%s\n" "$backup"
+  fi
+}
+
+restore_secrets() {
+  local src=$1 backup
+  if [[ -n $src ]]; then
+    backup=$(cat "$src")
+  else
+    backup=$(cat)
+  fi
+  info "Restoring keys & certs"
+  kubectl --context phxc apply -f <(printf "%s\n" "$backup")
+  info "Restarting cluster services"
+  kubectl --context phxc -n smallstep rollout restart statefulset phxc-ca
+  kubectl --context phxc -n smallstep wait --timeout=-1s --for=condition=Ready=false pod phxc-ca-0
+  kubectl --context phxc -n smallstep wait --timeout=-1s --for=condition=Ready pod phxc-ca-0
+  kubectl --context phxc -n smallstep rollout restart deployment step-issuer
+  info "Renewing all certificates that were issued by step-issuer"
+  local ns cert secret
+  while read -r -d $'\n' ns cert secret; do
+    info "Renewing %s/%s" "$ns" "$cert"
+    kubectl --context phxc -n "$ns" get secret "$secret" -ojson | \
+      clean_cert_secret | \
+      jq '.data["tls.crt"] |= "" | .data["ca.crt"] |= ""' | \
+      kubectl apply -f -
+    kubectl --context phxc -n "$ns" wait --timeout=-1s --for=condition=Ready certificate "$cert"
+  done < <(kubectl get --all-namespaces certificate -ojson | \
+    jq -r '.items[] | select(.spec.issuerRef == {"group": "certmanager.step.sm", "kind": "StepClusterIssuer", "name": "step-issuer"}) |
+      .metadata.namespace + " " + .metadata.name + " " + .spec.secretName')
+  kubectl --context phxc -n phxc rollout restart deployment image-registry
+  info "Trusting new restored certificate on all nodes and resigning SSH host keys"
+  local hostname
+  for hostname in $(kubectl --context phxc get nodes -ojsonpath='{.items[*].metadata.labels.kubernetes\.io/hostname}'); do
+    LC_ALL=C ssh -oStrictHostKeyChecking=accept-new "admin@$hostname" -- sudo systemctl restart --no-block workload-ready@smallstep workload-ready@image-registry trust-phxc-root sign-ssh-host-keys
+  done
+}
+
+clean_cert_secret() {
+  jq 'del(.metadata.annotations) | del(.metadata.labels) | del(.metadata.resourceVersion) | del(.metadata.uid)'
+}
+
+bootstrap() {
+  local variant=$1 wait=$2 job_name
+  job_name="build-$variant-$(date --utc +%Y%m%d%H%M%S)"
+  info "Creating job %s" "$job_name"
+  kubectl --context phxc -n phxc create job --from="cronjob/build-$variant" "$job_name"
+  if $wait; then
+    info "Waiting for %s to complete" "$job_name"
+    kubectl --context phxc -n phxc wait --timeout=-1s --for=condition=Complete job "$job_name"
+  fi
+}
+
+update_nodes() {
+  local nodes=("$@") node hostname logpid start_time
+  if ! kubectl get node -ojson | jq -e '.items[] | select(.spec.unschedulable) | length > 0' 2>&1 | LOGPROGRAM=step pipe_verbose; then
+    fatal "Unable to update any nodes. Some nodes are currently unschedulable"
+  fi
+  for node in "${nodes[@]}"; do
+    hostname=$(kubectl --context phxc get node "$node" -ojsonpath='{.metadata.labels.kubernetes\.io/hostname}')
+    info "Updating %s" "$node"
+    start_time=$(date "+%Y-%m-%d %H:%M:%S %z")
+    LC_ALL=C ssh "admin@$hostname" -- sudo systemctl start --no-block update-boot
+    LC_ALL=C ssh "admin@$hostname" -- journalctl -fu update-boot --since="\"$start_time\" --output=cat" & logpid=$!
+    # shellcheck disable=SC2064
+    trap "kill $logpid" EXIT
+    LC_ALL=C ssh "admin@$node" -- bash -c '"while [[ $(systemctl show -p SubState --value update-boot) != dead ]]; do sleep 1; done"'
+    kill $logpid
+    trap "" EXIT
+    # Node may be single master
+    until kubectl --context phxc -n phxc wait --timeout=-1s --for=condition=Ready node "$node"; do
+      info "Wait command failed, retrying in 10s (this may happen if the node that is updating is part of the control-plane)"
+      sleep 10
+    done
+  done
 }
 
 main "$@"
