Secureboot signing, booting, and cert enrollment working

diff --git a/bootstrap/root/usr/local/bin/update-boot b/bootstrap/root/usr/local/bin/update-boot
--- a/bootstrap/root/usr/local/bin/update-boot
+++ b/bootstrap/root/usr/local/bin/update-boot
@@ -4,10 +4,46 @@ set -Eeo pipefail; shopt -s inherit_errexit
 PKGROOT=/usr/local/lib/upkg/.upkg/phxc
 source "$PKGROOT/.upkg/records.sh/records.sh"
 
+case "${VARIANT:?}" in
+  amd64) EFI_ARCH=x64 ;;
+  arm64) EFI_ARCH=aa64 ;;
+  *) fatal "Unknown variant: %s" "$VARIANT" ;;
+esac
+
 main() {
-  [[ $# -eq 0 ]] || usage
+  source "$PKGROOT/.upkg/records.sh/records.sh"
+  DOC="update-boot - Update the boot partition with a new image
+Usage:
+  update-boot update
+  update-boot switch
+"
+# docopt parser below, refresh this parser with `docopt.sh update-boot`
+# shellcheck disable=2016,2086,2317,1090,1091,2034
+docopt() { local v='2.0.2'; source \
+"$PKGROOT/.upkg/docopt-lib-v$v/docopt-lib.sh" "$v" || { ret=$?;printf -- "exit \
+%d\n" "$ret";exit "$ret";};set -e;trimmed_doc=${DOC:0:105};usage=${DOC:57:48}
+digest=57a52;options=();node_0(){ switch update a:update;};node_1(){ switch \
+switch a:switch;};node_2(){ choice 0 1;};cat <<<' docopt_exit() { [[ -n $1 ]] \
+&& printf "%s\n" "$1" >&2;printf "%s\n" "${DOC:57:48}" >&2;exit 1;}';local \
+varnames=(update switch) varname;for varname in "${varnames[@]}"; do unset \
+"var_$varname";done;parse 2 "$@";local p=${DOCOPT_PREFIX:-''};for varname in \
+"${varnames[@]}"; do unset "$p$varname";done;eval $p'update=${var_update:-fals'\
+'e};'$p'switch=${var_switch:-false};';local docopt_i=1;[[ $BASH_VERSION =~ \
+^4.3 ]] && docopt_i=2;for ((;docopt_i>0;docopt_i--)); do for varname in \
+"${varnames[@]}"; do declare -p "$p$varname";done;done;}
+# docopt parser above, complete command for generating this parser is `docopt.sh --library='"$PKGROOT/.upkg/docopt-lib-v$v/docopt-lib.sh"' update-boot`
+  eval "$(docopt "$@")"
+  # shellcheck disable=SC2154
+  if $update; then
+    update
+  elif $switch; then
+    switch
+  fi
+}
+
+update() {
   local meta_json_new http_code
-  if ! meta_json_new=$(curl_img_reg "${VARIANT:?}/meta.json" -w '%{http_code}'); then
+  if ! meta_json_new=$(curl_img_reg "$VARIANT/meta.json" -w '%{http_code}'); then
     info "Unable to retrieve image metadata from image-registry"
     return 1
   fi
@@ -39,19 +75,39 @@ main() {
     return 0
   fi
   info "boot partition is outdated, updating now"
-  rm -f /boot/phxc/try.sha256 /boot/phxc/root.try.img /boot/EFI/Linux/uki.try.efi /boot/tryboot.img /run/initramfs/try-reboot
+  clean_update_boot_files
   # shellcheck disable=SC2064
-  trap "rm -f /run/initramfs/try-reboot /boot/phxc/try.sha256 /boot/phxc/root.try.img /boot/EFI/Linux/uki.try.efi /boot/tryboot.img" EXIT
+  trap "clean_update_boot_files" EXIT
   printf "%s" "$new_rootimg_sha256" >/boot/phxc/try.sha256
   curl_img_reg "$VARIANT/root.img" -o"/boot/phxc/root.${new_rootimg_sha256}.img" -f
   if [[ $VARIANT = rpi* ]]; then
     curl_img_reg "$VARIANT/boot.img" -o/boot/tryboot.img -f
   else
     curl_img_reg "$VARIANT/uki.efi" -o/boot/EFI/Linux/uki.try.efi -f
+    # Always update shim, mokmanager, and systemd-boot in case they have been updated (or systemd-boot has been signed)
+    # Haven't thought of a way to automatically fix them if an update is bungled though
+    curl_img_reg "$VARIANT/shim.efi" -o/boot/phxc/shim.efi.tmp -f
+    curl_img_reg "$VARIANT/mm.efi" -o/boot/phxc/mm.efi.tmp -f
+    curl_img_reg "$VARIANT/systemd-boot.efi" -o/boot/phxc/systemd-boot.efi.tmp -f
+    mv /boot/phxc/shim.efi.tmp /boot/EFI/BOOT/BOOT${EFI_ARCH^^}.efi
+    mv /boot/phxc/mm.efi.tmp /boot/EFI/BOOT/mm${EFI_ARCH^^}.efi
+    mv /boot/phxc/systemd-boot.efi.tmp /boot/EFI/BOOT/grub${EFI_ARCH^^}.efi
   fi
   info "boot partition has been updated"
   trap '' EXIT
   try_reboot
+}
+
+clean_update_boot_files() {
+  rm -f \
+    /run/initramfs/try-reboot \
+    /boot/phxc/try.sha256 \
+    /boot/phxc/root.try.img \
+    /boot/EFI/Linux/uki.try.efi \
+    /boot/tryboot.img \
+    /boot/phxc/shim.efi.tmp \
+    /boot/phxc/mm.efi.tmp \
+    /boot/phxc/systemd-boot.efi.tmp
 }
 
 try_reboot() {
@@ -82,6 +138,29 @@ try_reboot() {
   fi
 }
 
+switch() {
+  local current_rootimg_sha256 try_rootimg_sha256
+  current_rootimg_sha256=$(compgen -G /run/initramfs/root.*.img | cut -d. -f2)
+  try_rootimg_sha256=$(cat /boot/phxc/try.sha256 2>/dev/null || true)
+  if [[ $current_rootimg_sha256 = "$try_rootimg_sha256" ]]; then
+    info "Successfully booted new image"
+    if [[ $VARIANT = rpi* ]]; then
+      mv /boot/tryboot.img /boot/boot.img
+    else
+      mv /boot/EFI/Linux/uki.try.efi /boot/EFI/Linux/uki.efi
+    fi
+    local rootimg
+    for rootimg in /boot/phxc/root.*.img; do
+      [[ $rootimg = /boot/phxc/root.$try_rootimg_sha256.img ]] || rm "$rootimg"
+    done
+    rm /boot/phxc/try.sha256
+  else
+    error "Failed to boot new image"
+    rm -f /boot/tryboot.img /boot/EFI/Linux/uki.try.efi "/boot/phxc/root.$try_rootimg_sha256.img"
+    # Don't remove try.sha256, it prevents update-boot from retrying this specific image
+  fi
+}
+
 other_unschedulable_nodes() {
   kubectl get node -ojson | jq -re --arg hostname "$HOSTNAME" \
     '.items[] | select(.spec.unschedulable and .metadata.labels["kubernetes.io/hostname"] != $hostname) | .metadata.labels["kubernetes.io/hostname"]'
@@ -94,11 +173,6 @@ curl_img_reg() {
     -L --no-progress-meter --connect-timeout 5 \
     --retry 10 --retry-delay 60 \
     "https://image-registry.phxc.svc.cluster.local:8020/$path" "$@"
-}
-
-usage() {
-  printf "Usage: update-boot\n" >&2
-  return 1
 }
 
 main "$@"
