node: Switch from initramfs-tools to dracut

diff --git a/workloads/node/bootstrap/assets/usr/lib/dracut/modules.d/99home-cluster/bin/find-boot-server b/workloads/node/bootstrap/assets/usr/lib/dracut/modules.d/99home-cluster/bin/find-boot-server
--- a/workloads/node/bootstrap/assets/usr/lib/dracut/modules.d/99home-cluster/bin/find-boot-server
+++ b/workloads/node/bootstrap/assets/usr/lib/dracut/modules.d/99home-cluster/bin/find-boot-server
@@ -1,14 +1,9 @@
 #!/usr/bin/env bash
 set -Eeo pipefail; shopt -s inherit_errexit
-[[ $1 != prereqs ]] || { echo ""; exit 0; }
-
-PKGROOT=$(realpath "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/..")
-# shellcheck source=../common.sh
-source "$PKGROOT/common.sh"
+# shellcheck source=../lib/shellcheck-common.sh
+source /usr/lib/home-cluster/common.sh
 
 main() {
-  sh -c '. /scripts/functions; configure_networking'
-
   # Broadcast a DHCPDISCOVER packet on port 4011 to get an answer from dhcp-proxy
   # Built with make-req.py
   local dhcp_discover_head='01010600'
@@ -46,7 +41,7 @@ main() {
           "${mac//:/}" \
           "$dhcp_discover_mac_tail" | \
         xxd -r -p | \
-        socat - udp-datagram:255.255.255.255:4011,bind=:0,broadcast,reuseaddr | \
+        socat -4 - udp-datagram:255.255.255.255:4011,bind=:0,broadcast,reuseaddr | \
         dd skip=1 count=1 ibs=44 obs=64 status=none | tr -d '\000'
       ) && [[ -n "$boot_server" ]]; then
       info "Found boot-server at $boot_server"
@@ -55,7 +50,7 @@ main() {
       break
     fi
   done
-  [[ -n "$boot_server" ]] || warning "Unable to find the boot-server"
+  [[ -n "$boot_server" ]] || fatal "Unable to find the boot-server"
 }
 
 main "$@"
