Fix networking, timezone, and scripts in general

diff --git a/config/scripts/K8S/50-k3s b/config/scripts/K8S/50-k3s
--- a/config/scripts/K8S/50-k3s
+++ b/config/scripts/K8S/50-k3s
@@ -1,3 +1,8 @@
 #!/usr/bin/env bash
 
+error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code
+$ROOTCMD wget -SO /dev/null https://update.k3s.io/v1-release/channels/stable
+export INSTALL_K3S_SKIP_START=true
 curl -sfL https://get.k3s.io | $ROOTCMD sh -
+
+exit $error
