node: Remove need for specifying bootServer IP, unifi tftpd & httpd and use dhcp lease info instead

diff --git a/workloads/node/bootstrap/assets/etc/initramfs-tools/scripts/init-bottom/authenticate b/workloads/node/bootstrap/assets/etc/initramfs-tools/scripts/init-bottom/authenticate
--- a/workloads/node/bootstrap/assets/etc/initramfs-tools/scripts/init-bottom/authenticate
+++ b/workloads/node/bootstrap/assets/etc/initramfs-tools/scripts/init-bottom/authenticate
@@ -9,21 +9,10 @@ esac
 # shellcheck disable=SC1091
 . /scripts/functions
 
-# shellcheck disable=SC2013
-for x in $(cat /proc/cmdline); do
-  case $x in
-  bootserver=*)
-    bootserver=${x#bootserver=}
-    ;;
-  esac
-done
-if [ -z "${bootserver}" ]; then
-  log_warning_msg "Skipping cluster authentication. Boot argument bootserver= not specified, unable to contact bootserver"
+set +e; configure_networking; set -e
+if [ -n "$ROOTSERVER" ]; then
+  /usr/local/lib/upkg/.upkg/home-cluster/workloads/node/bin/safeboot-attest "http://${ROOTSERVER}/attest"
+else
+  log_warning_msg "Skipping cluster authentication: ROOTSERVER/NEXT_SERVER not found in DHCP lease"
   exit 1
 fi
-
-set +e; configure_networking; set -e
-
-/usr/local/lib/upkg/.upkg/home-cluster/workloads/node/bin/safeboot-attest "http://${bootserver}/attest"
-
-exit 1
diff --git a/workloads/node/bootstrap/assets/etc/initramfs-tools/scripts/init-bottom/settings b/workloads/node/bootstrap/assets/etc/initramfs-tools/scripts/init-bottom/settings
--- a/workloads/node/bootstrap/assets/etc/initramfs-tools/scripts/init-bottom/settings
+++ b/workloads/node/bootstrap/assets/etc/initramfs-tools/scripts/init-bottom/settings
@@ -9,24 +9,15 @@ esac
 # shellcheck disable=SC1091
 . /scripts/functions
 
-# shellcheck disable=SC2013
-for x in $(cat /proc/cmdline); do
-  case $x in
-  bootserver=*)
-    bootserver=${x#bootserver=}
-    ;;
-  esac
-done
-if [ -z "${bootserver}" ]; then
-  log_warning_msg "Skipping download/copy of settings. Boot argument bootserver= not specified, unable to determine MAC address"
+set +e; configure_networking; set -e
+if [ -z "$ROOTSERVER" ]; then
+  log_warning_msg "Skipping download/copy of settings: ROOTSERVER not found in DHCP lease"
   exit 1
 fi
 
-set +e; configure_networking; set -e
-
 # Get the NIC MAC we use to contact the boot server
-if ! link=$(ip -o route get to "$bootserver" | grep -Eo 'dev [^ ]+' | cut -d ' ' -f2); then
-  log_failure_msg "Unable to determine interface used to contact $bootserver, aborting node-settings.json download/copy"
+if ! link=$(ip -o route get to "$ROOTSERVER" | grep -Eo 'dev [^ ]+' | cut -d ' ' -f2); then
+  log_failure_msg "Unable to determine interface used to contact $ROOTSERVER, aborting node-settings.json download/copy"
   exit 1
 fi
 if ! mac=$(ip link show "$link" | tail -n1 | grep -Eo '([a-f0-9]{2}:){5}[a-f0-9]{2}' | head -n1); then
@@ -36,7 +27,7 @@ fi
 
 settings_filename=$(printf "%s" "$mac" | sed s/:/-/g).json
 settings_path=/run/initramfs/node-settings.json
-settings_url=http://$bootserver/$settings_filename
+settings_url=http://$ROOTSERVER/$settings_filename
 
 log_begin_msg "Downloading settings from $settings_url"
 if curl -fsL --connect-timeout 5 --retry 3 -o "$settings_path" "$settings_url"; then
@@ -49,7 +40,7 @@ fi
 esp=/run/initramfs/efi
 if [ -e $esp ]; then
   log_begin_msg "Falling back to copying settings from ESP mount instead"
-  if cp "/run/initramfs/efi/home-cluster/node-settings/$settings_filename" "$settings_path"; then
+  if cp "$esp/home-cluster/node-settings/$settings_filename" "$settings_path"; then
     log_end_msg
     exit 0
   else
diff --git a/workloads/node/bootstrap/assets/etc/initramfs-tools/scripts/local-premount/rootimg b/workloads/node/bootstrap/assets/etc/initramfs-tools/scripts/local-premount/rootimg
--- a/workloads/node/bootstrap/assets/etc/initramfs-tools/scripts/local-premount/rootimg
+++ b/workloads/node/bootstrap/assets/etc/initramfs-tools/scripts/local-premount/rootimg
@@ -8,15 +8,6 @@ esac
 # shellcheck disable=SC1091
 . /scripts/functions
 
-# shellcheck disable=SC2013
-for x in $(cat /proc/cmdline); do
-  case $x in
-  bootserver=*)
-    bootserver=${x#bootserver=}
-    ;;
-  esac
-done
-
 rootimg_path=/run/initramfs/root.img
 # shellcheck disable=SC2013
 for x in $(cat /proc/cmdline); do
@@ -47,26 +38,25 @@ if [ -e $esp/home-cluster/root.img ]; then
   if cp $esp/home-cluster/root.img $rootimg_path.tmp; then
     log_end_msg
     verify_rootimg
-    exit 0
   else
     log_failure_msg "Failed to copy root.img"
     exit 1
   fi
-fi
-
-if [ -n "${bootserver}" ]; then
+else
   set +e; configure_networking; set -e
-  img_addr=http://${bootserver}/$(uname -m)/root.img
-  log_begin_msg "Downloading root image to RAM from $img_addr"
-  if ! curl -fsL --connect-timeout 5 --retry 3 -o $rootimg_path.tmp "$img_addr"; then
-    log_end_msg
-    verify_rootimg
-    exit 0
+  if [ -n "$ROOTSERVER" ]; then
+    img_addr=http://${ROOTSERVER}/$(uname -m)/root.img
+    log_begin_msg "Downloading root image to RAM from $img_addr"
+    if ! curl -fsL --connect-timeout 5 --retry 3 -o $rootimg_path.tmp "$img_addr"; then
+      log_end_msg
+      verify_rootimg
+      exit 0
+    else
+      log_failure_msg "Failed to download root.img: Download failed"
+      exit 1
+    fi
   else
-    log_failure_msg "Failed to download root.img: Download failed"
+    log_failure_msg "Failed to download root.img: ROOTSERVER/NEXT_SERVER not found in DHCP lease"
     exit 1
   fi
-else
-  log_warning_msg "Failed to download root image: Boot argument bootserver= not specified"
-  exit 1
 fi
