node: Use machine-id instead of primary-mac as machine primary key

diff --git a/workloads/node/bootstrap/assets/usr/local/bin/download-node-config b/workloads/node/bootstrap/assets/usr/local/bin/download-node-config
--- a/workloads/node/bootstrap/assets/usr/local/bin/download-node-config
+++ b/workloads/node/bootstrap/assets/usr/local/bin/download-node-config
@@ -10,35 +10,26 @@ main() {
   fi
   [[ $# -le 1 ]] || usage
   local node_config_dest=$1 jwt retry=15 node_config
-  if get-node-state primary-mac &>/dev/null; then
-    while true; do
-      if boot-server-available; then
-        jwt=$(sign-jwt node-config)
-        if node_config=$(curl-boot-server "registry/config?jwt=$jwt"); then
-          printf "Successfully downloaded node-config\n" >&2
-          break
-        else
-          printf "Failed to download node-config, retrying in %ds\n" "$retry" >&2
-        fi
+  while true; do
+    if boot-server-available; then
+      jwt=$(sign-jwt node-config)
+      if node_config=$(curl-boot-server "registry/config?jwt=$jwt"); then
+        printf "Successfully downloaded node-config\n" >&2
+        break
       else
-        if [[ -e /boot/home-cluster/node-config.json.enc ]] && $allow_fallback; then
-          printf "boot-server is not available and cached node-config exists, using that instead\n" >&2
-          node_config=$(systemd-creds decrypt /boot/home-cluster/node-config.json.enc)
-          break
-        else
-          printf "boot-server is not available, retrying in %ds\n" "$retry" >&2
-        fi
+        printf "Failed to download node-config, retrying in %ds\n" "$retry" >&2
       fi
-      sleep $retry
-    done
-  else
-    if [[ -e /boot/home-cluster/node-config.json.enc ]] && $allow_fallback; then
-      printf "Cached node-config exists, using that instead\n" >&2
-      node_config=$(systemd-creds decrypt /boot/home-cluster/node-config.json.enc)
     else
-      return 1
+      if [[ -e /boot/home-cluster/node-config.json.enc ]] && $allow_fallback; then
+        printf "boot-server is not available and cached node-config exists, using that instead\n" >&2
+        node_config=$(systemd-creds decrypt /boot/home-cluster/node-config.json.enc)
+        break
+      else
+        printf "boot-server is not available, retrying in %ds\n" "$retry" >&2
+      fi
     fi
-  fi
+    sleep $retry
+  done
   if [[ -z $node_config_dest || $node_config_dest = '-' ]]; then
     printf "%s\n" "$node_config"
   else
