Fix k3s startup

diff --git a/workloads/node/bootstrap/assets/usr/local/bin/get-config b/workloads/node/bootstrap/assets/usr/local/bin/get-config
--- a/workloads/node/bootstrap/assets/usr/local/bin/get-config
+++ b/workloads/node/bootstrap/assets/usr/local/bin/get-config
@@ -3,19 +3,22 @@ set -Eeo pipefail; shopt -s inherit_errexit
 
 main() {
   local e; for e; do [[ "$e" != "--help" ]] || usage; done
-  [[ -n $1 && -n $2 && $# -ge 2 && $# -le 4 ]] || usage
+  [[ -n $1 && $# -ge 1 && $# -le 4 ]] || usage
   local quiet=false
   if [[ $1 = '-q' ]]; then quiet=true; shift; fi
   local filepath=$1 key=$2 default=$3 real_filepath contents schema
-  schema=$(basename "$filepath")
+  schema=$(basename "$filepath" .yaml)
   if [[ -e $filepath ]]; then
     real_filepath=$(realpath "$filepath")
     contents=$(cat "$real_filepath")
-    if [[ $real_filepath = /boot/* ]] && ! ssh-keygen -Y verify -f <(sed 's/^/admin /g' </home/admin/authorized_keys) -I admin -n file -s "$real_filepath.sig" <<<"$contents"; then
-      printf "Failed to verify signature of %s using /home/admin/authorized_keys\n" "$real_filepath" >&2
+    if [[ $real_filepath = /boot/* ]] && ! ssh-keygen -q -Y verify -f <(sed 's/^/admin /g' </home/admin/.ssh/authorized_keys) -I admin -n file -s "$real_filepath.sig" <<<"$contents"; then
+      printf "Failed to verify signature of %s using /home/admin/.ssh/authorized_keys\n" "$real_filepath" >&2
       return 1
     fi
-    jsonschema -i <(printf "%s\n" "$contents") <(yq . "/usr/local/lib/phxc/schemas/$schema.schema.yaml")
+    local validation_errors
+    if ! validation_errors=$(jsonschema -i <(yq . <<<"$contents") <(yq . "/usr/local/lib/phxc/schemas/$schema.schema.yaml") 2>&1); then
+      fatal 'Failed to validate "%s". Errors: %s' "$filepath" "$validation_errors"
+    fi
     if [[ -n $key ]]; then
       if yq -r 'paths | join(".")' <<<"$contents" | grep -q "^$key$"; then
         key=$(escape_key "$key")
@@ -27,7 +30,7 @@ main() {
         return 1
       fi
     else
-      cat "$filepath"
+      printf "%s\n" "$contents"
     fi
   elif [[ -n $default ]]; then
     printf "%s\n" "$default"
