node: Fix uses of fatal()

diff --git a/workloads/node/bootstrap/assets/usr/local/bin/partition-disk b/workloads/node/bootstrap/assets/usr/local/bin/partition-disk
--- a/workloads/node/bootstrap/assets/usr/local/bin/partition-disk
+++ b/workloads/node/bootstrap/assets/usr/local/bin/partition-disk
@@ -5,7 +5,10 @@ main() {
   local devpath
   devpath=$(get-node-config disk.devpath)
   if sfdisk -J "$devpath" &>/dev/null || lsblk -Jndo FSTYPE "$devpath" | jq -re '.blockdevices[0].fstype != null' >/dev/null; then
-    [[ $(get-node-config disk.force) = true ]] || fatal "Device %s is partitioned or contains a filesystem and .disk.force != true, aborting disk setup" "$devpath"
+    if [[ $(get-node-config disk.force) != true ]]; then
+      printf "Device %s is partitioned or contains a filesystem and .disk.force != true, aborting disk setup\n" "$devpath" >&2
+      return 1
+    fi
   fi
   printf 'Partitioning disk at "%s"\n' "$devpath" >&2
   wipefs -a "$devpath"
diff --git a/workloads/node/bootstrap/assets/usr/local/bin/update-boot b/workloads/node/bootstrap/assets/usr/local/bin/update-boot
--- a/workloads/node/bootstrap/assets/usr/local/bin/update-boot
+++ b/workloads/node/bootstrap/assets/usr/local/bin/update-boot
@@ -6,7 +6,8 @@ main() {
   local digests_json_new
   mkdir -p /boot/home-cluster
   if ! digests_json_new=$(curl-boot-server "images/$VARIANT/digests.json"); then
-    fatal "Unable to retrieve image digests from boot server"
+    printf "Unable to retrieve image digests from boot server\n" >&2
+    return 1
   fi
   local current_root_img_sha256 new_root_img_sha256
   current_root_img_sha256=$(jq -re '.sha256sums["root.img"]' /boot/home-cluster/digests.json 2>/dev/null || true)
@@ -32,7 +33,7 @@ main() {
     case $VARIANT in
       amd64) efipath=/boot/EFI/BOOT/BOOTX64.efi ;;
       arm64) efipath=/boot/EFI/BOOT/BOOTAA64.efi ;;
-      *) fatal "Unknown variant: %s" "$VARIANT" ;;
+      *) printf "Unknown variant: %s\n" "$VARIANT" >&2; return 1 ;;
     esac
     mkdir -p /boot/EFI/BOOT
     if curl-boot-server "images/$VARIANT/uki.efi" -o$efipath.new ; then
