node: Use systemd-creds for encrypting authentication key
This way we can leverage TPM2 more easily

diff --git a/workloads/node/bootstrap/assets/usr/local/bin/report-node-state b/workloads/node/bootstrap/assets/usr/local/bin/report-node-state
--- a/workloads/node/bootstrap/assets/usr/local/bin/report-node-state
+++ b/workloads/node/bootstrap/assets/usr/local/bin/report-node-state
@@ -4,15 +4,14 @@ set -Eeo pipefail; shopt -s inherit_errexit
 main() {
   local primary_mac node_state_sig node_state result
   primary_mac=$(get-node-state primary-mac) || return 1
-  printf "%s\n" "$(jq -c --sort-keys . /run/initramfs/node-state.json | tr -d '\n')"
-  node_state_sig=$(jq -c --sort-keys . /run/initramfs/node-state.json | tr -d '\n' | openssl dgst -sha256 -sign /run/initramfs/node-key | base64 -w0) || return 1
+  node_state_sig=$(jq -c --sort-keys . /run/initramfs/node-state.json | tr -d '\n' | openssl dgst -sha256 -sign /run/initramfs/authn.key | base64 -w0) || return 1
   node_state=$(jq --arg sig "$node_state_sig" '.signature=$sig' /run/initramfs/node-state.json) || return 1
   if result=$(curl-boot-server "registry/node-states/${primary_mac//:/-}.json" \
     -XPUT -d@<(printf "%s" "$node_state") -w '%{http_code}' | tail -n1); then
     return 0
   else
     if [[ $result = 403 ]]; then
-      printf "Reporting node-state not possible, node-key is invalid\n" >&2
+      printf "Reporting node-state not possible, authentication key is invalid\n" >&2
       return 1
     else
       printf "Failed to report node-state\n" >&2
