Fix bugs after refactor
Also implement switch to new image after boot

diff --git a/workloads/node/bootstrap/assets/usr/local/bin/try-reboot b/workloads/node/bootstrap/assets/usr/local/bin/try-reboot
--- a/workloads/node/bootstrap/assets/usr/local/bin/try-reboot
+++ b/workloads/node/bootstrap/assets/usr/local/bin/try-reboot
@@ -4,30 +4,31 @@ set -Eeo pipefail; shopt -s inherit_errexit
 main() {
   local e; for e; do [[ "$e" != "--help" ]] || usage; done
   [[ $# -eq 1 ]] || usage
+  touch /run/initramfs/try-reboot
   case "$1" in
     try)
-    [[ -e /boot/phxc/root.try.img ]] || { printf "try-reboot: /boot/phxc/root.try.img does not exist\n" >&2; return 1; }
-    case ${VARIANT:?} in
-      rpi*)
-      # https://www.raspberrypi.com/documentation/computers/config_txt.html#the-tryboot-filter
-      [[ -e /boot/tryboot.img ]] || { printf "try-reboot: /boot/tryboot.img does not exist\n" >&2; return 1; }
+      if [[ $VARIANT = rpi* ]]; then
+        # https://www.raspberrypi.com/documentation/computers/config_txt.html#the-tryboot-filter
+        [[ -e /boot/tryboot.img ]] || { printf "try-reboot: /boot/tryboot.img does not exist\n" >&2; return 1; }
+      else
+        # https://manpages.debian.org/bookworm/systemd-boot/bootctl.1.en.html#BOOT_LOADER_SPECIFICATION_COMMANDS
+        [[ -e /boot/EFI/Linux/uki.try.efi ]] || { printf "try-reboot: /boot/EFI/Linux/uki.try.efi does not exist\n" >&2; return 1; }
+      fi
       get_lease
-      reboot "0 tryboot"
-      ;;
-      *)
-      # https://manpages.debian.org/bookworm/systemd-boot/bootctl.1.en.html#BOOT_LOADER_SPECIFICATION_COMMANDS
-      [[ -e /boot/EFI/Linux/uki.try.efi ]] || { printf "try-reboot: /boot/EFI/Linux/uki.try.efi does not exist\n" >&2; return 1; }
-      bootctl set-oneshot uki.try.efi
-      systemctl reboot
-      ;;
-    esac
+      if [[ -e /run/initramfs/try-reboot ]]; then
+        if [[ $VARIANT = rpi* ]]; then
+          reboot "0 tryboot"
+        else
+          bootctl set-oneshot uki.try.efi
+          systemctl reboot
+        fi
+      else
+        printf "try-reboot: /run/initramfs/try-reboot no longer exists, aborting\n" >&2
+        clear_lease
+        return 1
+      fi
     ;;
-    clear)
-    local holder_id
-    if holder_id=$(kubectl -n node get lease reboot -ojsonpath='{.spec.holderIdentity}') && [[ $holder_id = $(cat /etc/machine-id) ]]; then
-      kubectl -n node delete lease reboot
-    fi
-    ;;
+    clear) clear_lease ;;
   esac
 }
 
@@ -41,6 +42,15 @@ metadata:
   namespace: node') 2>/dev/null; do
     sleep 60
   done
+  printf "try-reboot: Reboot lease acquired\n" >&2
+}
+
+clear_lease() {
+  local holder_id
+  if holder_id=$(kubectl -n node get lease reboot -ojsonpath='{.spec.holderIdentity}') && [[ $holder_id = $(cat /etc/machine-id) ]]; then
+    kubectl -n node delete lease reboot
+    printf "try-reboot: Reboot lease cleared\n" >&2
+  fi
 }
 
 usage() {
diff --git a/workloads/node/bootstrap/assets/usr/local/bin/update-boot b/workloads/node/bootstrap/assets/usr/local/bin/update-boot
--- a/workloads/node/bootstrap/assets/usr/local/bin/update-boot
+++ b/workloads/node/bootstrap/assets/usr/local/bin/update-boot
@@ -5,37 +5,37 @@ main() {
   [[ $# -eq 0 ]] || usage
   local meta_json_new
   if ! meta_json_new=$(curl_img_reg "${VARIANT:?}/meta.json"); then
-    printf "Unable to retrieve image metadata from boot server\n" >&2
+    printf "update-boot: Unable to retrieve image metadata from image-registry\n" >&2
     return 1
   fi
-  local current_root_img_sha256 try_root_img_sha256 new_root_img_sha256
-  current_root_img_sha256=$(sha256sum /run/initramfs/root.img)
-  try_root_img_sha256=$(sha256sum /boot/phxc/root.try.img 2>/dev/null || true)
-  new_root_img_sha256=$(jq -re '.sha256sums["root.img"]' <<<"$meta_json_new")
-  if [[ $current_root_img_sha256 = "$new_root_img_sha256" ]]; then
-    printf "boot partition is up-to-date (image is currently running)\n" >&2
+  local current_rootimg_sha256 try_rootimg_sha256 new_rootimg_sha256
+  current_rootimg_sha256=$(compgen -G /run/initramfs/root.*.img | cut -d. -f2)
+  try_rootimg_sha256=$(cat /boot/phxc/try.sha256 2>/dev/null || true)
+  new_rootimg_sha256=$(jq -re '.sha256sums["root.img"]' <<<"$meta_json_new")
+  if [[ $current_rootimg_sha256 = "$new_rootimg_sha256" ]]; then
+    printf "update-boot: boot partition is up-to-date (image is currently running)\n" >&2
     return 0
   fi
-  if [[ $try_root_img_sha256 = "$new_root_img_sha256" ]]; then
+  if [[ $try_rootimg_sha256 = "$new_rootimg_sha256" ]]; then
     if [[ -e /run/initramfs/try-reboot ]]; then
-      printf "boot partition is up-to-date (image will be tried)\n" >&2
+      printf "update-boot: boot partition is up-to-date (newer image will be tried)\n" >&2
     else
-      printf "boot partition is up-to-date (image failed to boot)\n" >&2
+      printf "update-boot: boot partition is up-to-date (newer image failed to boot)\n" >&2
     fi
     return 0
   fi
-  printf "boot partition is outdated, updating now\n" >&2
-  rm -f /boot/phxc/root.try.img /boot/EFI/Linux/uki.try.efi /boot/tryboot.img
+  printf "update-boot: boot partition is outdated, updating now\n" >&2
+  rm -f /boot/phxc/try.sha256 /boot/phxc/root.try.img /boot/EFI/Linux/uki.try.efi /boot/tryboot.img /run/initramfs/try-reboot
   # shellcheck disable=SC2064
-  trap "rm -f /boot/phxc/root.try.img /boot/EFI/Linux/uki.try.efi" EXIT
-  curl_img_reg "$VARIANT/root.img" -o/boot/phxc/root.try.img
+  trap "rm -f /run/initramfs/try-reboot /boot/phxc/try.sha256 /boot/phxc/root.try.img /boot/EFI/Linux/uki.try.efi /boot/tryboot.img /run/initramfs/try-reboot" EXIT
+  printf "%s" "$new_rootimg_sha256" >/boot/phxc/try.sha256
+  curl_img_reg "$VARIANT/root.img" -o"/boot/phxc/root.${new_rootimg_sha256}.img"
   if [[ $VARIANT = rpi* ]]; then
     curl_img_reg "$VARIANT/boot.img" -o/boot/tryboot.img
   else
     curl_img_reg "$VARIANT/uki.efi" -o/boot/EFI/Linux/uki.try.efi
   fi
-  touch /run/initramfs/try-reboot
-  printf "boot partition has been updated\n" >&2
+  printf "update-boot: boot partition has been updated\n" >&2
   trap '' EXIT
   try-reboot
 }
