update-boot: Make meta.json 404 not an error (image hasn't been built yet)

diff --git a/workloads/node/bootstrap/assets/usr/local/bin/update-boot b/workloads/node/bootstrap/assets/usr/local/bin/update-boot
--- a/workloads/node/bootstrap/assets/usr/local/bin/update-boot
+++ b/workloads/node/bootstrap/assets/usr/local/bin/update-boot
@@ -3,11 +3,21 @@ set -Eeo pipefail; shopt -s inherit_errexit
 
 main() {
   [[ $# -eq 0 ]] || usage
-  local meta_json_new
-  if ! meta_json_new=$(curl_img_reg "${VARIANT:?}/meta.json"); then
+  local meta_json_new http_code
+  if ! meta_json_new=$(curl_img_reg "${VARIANT:?}/meta.json" -w '%{http_code}'); then
     printf "update-boot: Unable to retrieve image metadata from image-registry\n" >&2
     return 1
   fi
+  http_code=$(tail -n1 <<<"$meta_json_new")
+  if [[ $http_code = 404 ]]; then
+    printf "update-boot: No image has been built for the variant '%s' yet\n" "$VARIANT" >&2
+    return 0
+  fi
+  if [[ $http_code != 200 ]]; then
+    printf "update-boot: Unable to retrieve image metadata from image-registry (HTTP response code %s)\n" "$http_code" >&2
+    return 1
+  fi
+  meta_json_new=$(head -n-1 <<<"$meta_json_new")
   local current_rootimg_sha256 try_rootimg_sha256 new_rootimg_sha256
   current_rootimg_sha256=$(compgen -G /run/initramfs/root.*.img | cut -d. -f2)
   try_rootimg_sha256=$(cat /boot/phxc/try.sha256 2>/dev/null || true)
@@ -29,11 +39,11 @@ main() {
   # shellcheck disable=SC2064
   trap "rm -f /run/initramfs/try-reboot /boot/phxc/try.sha256 /boot/phxc/root.try.img /boot/EFI/Linux/uki.try.efi /boot/tryboot.img /run/initramfs/try-reboot" EXIT
   printf "%s" "$new_rootimg_sha256" >/boot/phxc/try.sha256
-  curl_img_reg "$VARIANT/root.img" -o"/boot/phxc/root.${new_rootimg_sha256}.img"
+  curl_img_reg "$VARIANT/root.img" -o"/boot/phxc/root.${new_rootimg_sha256}.img" -f
   if [[ $VARIANT = rpi* ]]; then
-    curl_img_reg "$VARIANT/boot.img" -o/boot/tryboot.img
+    curl_img_reg "$VARIANT/boot.img" -o/boot/tryboot.img -f
   else
-    curl_img_reg "$VARIANT/uki.efi" -o/boot/EFI/Linux/uki.try.efi
+    curl_img_reg "$VARIANT/uki.efi" -o/boot/EFI/Linux/uki.try.efi -f
   fi
   printf "update-boot: boot partition has been updated\n" >&2
   trap '' EXIT
@@ -44,7 +54,7 @@ curl_img_reg() {
   local path=$1
   shift
   curl --cacert /usr/local/share/ca-certificates/phoenix-cluster-root.crt \
-    -fL --no-progress-meter --connect-timeout 5 \
+    -L --no-progress-meter --connect-timeout 5 \
     --retry 10 --retry-delay 60 \
     "https://image-registry.node.svc.cluster.local:8020/$path" "$@"
 }
