node: Implement whitelisting of image digests and EK hashes

diff --git a/workloads/node/scripts/safeboot-attest/attest-verify b/workloads/node/scripts/safeboot-attest/attest-verify
--- a/workloads/node/scripts/safeboot-attest/attest-verify
+++ b/workloads/node/scripts/safeboot-attest/attest-verify
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 # shellcheck source-path=../../../..
-set -Eeo pipefail; shopt -s inherit_errexit
+set -Eeo pipefail; shopt -s inherit_errexit nullglob
 PKGROOT=/usr/local/lib/upkg
 
 main() {
@@ -28,30 +28,37 @@ varname in "${varnames[@]}"; do declare -p "$p$varname";done;done;}
 
   local pcr4_sha256
   pcr4_sha256=$(yq -r '.pcrs.sha256["4"]' "$PAYLOAD_DIR/quote.yaml")
+  # Lowercase with ",,"
+  pcr4_sha256=${pcr4_sha256,,}
   if ! find_pcr4_match "$EK_HASH" "$pcr4_sha256"; then
-    fatal "%s: Unable to find match for PCR 4 among known images" "$EK_HASH"
+    fatal "%s: Unable to find match for PCR 4 amongst known or whitelisted images" "$EK_HASH"
   fi
 
-  # TODO: verify EK
+  if ! is_ek_whitelisted "$EK_HASH"; then
+    add_pending_ek "$EK_HASH"
+    fatal "%s: The endorsement key is not whitelisted" "$EK_HASH"
+  else
+    verbose "The endorsement key is whitelisted" "$EK_HASH"
+  fi
 
   return 0
 }
 
 find_pcr4_match() {
   # Lowercase with ",,"
-  local EK_HASH=$1 pcr4_sha256=${2,,} \
-    init_sha256 start_sha256 barrier_sha256
-  init_sha256=$(printf "0000000000000000000000000000000000000000000000000000000000000000")
-  start_sha256=$(printf "Calling EFI Application from Boot Option" | sha256)
-  barrier_sha256=$(printf "00000000" | xxd -r -p | sha256)
-  local imgdir sha256_shim sha256_vmlinuz sha256_candidate
-  for imgdir in /images/*; do
-    [[ -e "$imgdir/shim.efi.digest.json" && -e "$imgdir/vmlinuz.efi.digest.json" ]] || continue
-    sha256_shim=$(jq -r '.sha256' "$imgdir/shim.efi.digest.json")
-    sha256_vmlinuz=$(jq -r '.sha256' "$imgdir/vmlinuz.efi.digest.json")
-    sha256_candidate=$(sha256_extend "$init_sha256" "$start_sha256" "$barrier_sha256" "$sha256_shim" "$sha256_vmlinuz")
-    if [[ $pcr4_sha256 = "$sha256_candidate" ]]; then
-      info "%s: SHA256 of PCR4 matches image at %s" "$EK_HASH" "$imgdir"
+  local EK_HASH=$1 pcr4_sha256=$2 digestfile
+  verbose "Finding match for PCR 4 SHA256 %s" "$pcr4_sha256"
+  for digestfile in /images/*/digests.json; do
+    verbose "Checking against own image: %s" "$(basename "$(dirname "$digestfile")")"
+    if check_pcr4_match "$digestfile" "$pcr4_sha256"; then
+      info "%s: SHA256 of PCR4 matches image at %s" "$EK_HASH" "$digestfile"
+      return 0
+    fi
+  done
+  for digestfile in /attestation-database/pcr-whitelist/*; do
+    verbose "Checking whitelisted digest: %s" "$(basename "$digestfile")"
+    if check_pcr4_match "$digestfile" "$pcr4_sha256"; then
+      info "%s: SHA256 of PCR4 matches whitelist at %s" "$EK_HASH" "$digestfile"
       return 0
     fi
   done
@@ -60,6 +67,39 @@ find_pcr4_match() {
 
 sha256() {
   sha256sum | cut -d ' ' -f1
+}
+
+init_sha256=$(printf "0000000000000000000000000000000000000000000000000000000000000000")
+start_sha256=$(printf "Calling EFI Application from Boot Option" | sha256)
+barrier_sha256=$(printf "00000000" | xxd -r -p | sha256)
+check_pcr4_match() {
+  local digestfile=$1 pcr4_sha256=$2 shim_sha256 uki_sha256 kernel_sha256
+  read -rd ' ' shim_sha256 uki_sha256 kernel_sha256 < <(jq -r '.shim.sha256, .uki.sha256, .kernel.sha256' "$digestfile")
+  verbose "Checking against UKI SHA256: %s" "$uki_sha256"
+  [[ $pcr4_sha256 != "$(sha256_extend "$init_sha256" "$start_sha256" "$barrier_sha256" "$shim_sha256" "$uki_sha256")" ]] || return 0
+  [[ $pcr4_sha256 != "$(sha256_extend "$init_sha256" "$start_sha256" "$barrier_sha256" "$shim_sha256" "$uki_sha256" "$kernel_sha256")" ]] || return 0
+  return 1
+}
+
+is_ek_whitelisted() {
+  local EK_HASH=$1 ek_whitelist=/attestation-database/ek-whitelist.json
+  if [[ -z $(cat "$ek_whitelist" 2>/dev/null) ]]; then
+    printf '[]\n' >"$ek_whitelist"
+  fi
+  jq -re --arg ek_hash "$EK_HASH" 'index($ek_hash)!=null' "$ek_whitelist" &>/dev/null
+}
+
+add_pending_ek() {
+  local EK_HASH=$1 ek_pending=/attestation-database/ek-pending.json
+  if [[ -z $(cat "$ek_pending" 2>/dev/null) ]]; then
+    printf '[]\n' >"$ek_pending"
+  fi
+  if ! jq -re --arg ek_hash "$EK_HASH" 'index($ek_hash)!=null' "$ek_pending" &>/dev/null; then
+    local new_pending
+    info "%s: Adding to list of pending endorsement keys" "$EK_HASH"
+    new_pending=$(jq --arg ek_hash "$EK_HASH" '. += [$ek_hash]' "$ek_pending")
+    printf "%s\n" "$new_pending" >"$ek_pending"
+  fi
 }
 
 sha256_extend() {
